package com.brewtech.decidr.intelligence

import com.brewtech.decidr.voice.QuestionCategory
import kotlin.random.Random

/**
 * Markov chain text generator trained on the Oracle corpus.
 *
 * Uses a trigram (order-2) model where each state is a pair of consecutive words
 * and transitions represent the probability of each possible next word.
 * The chain is pre-computed from 260 training sentences and embedded directly
 * as Kotlin data structures -- no external files or JSON parsing needed.
 */
class MarkovGenerator(private val random: Random = Random.Default) {

    /**
     * Temperature controls randomness of word selection.
     * 0.0 = always pick the most likely next word (deterministic).
     * 1.0 = sample proportionally to frequency (natural randomness).
     * Values above 1.0 flatten the distribution (more surprising).
     */
    var temperature: Double = 0.7

    private val transitions: Map<Pair<String, String>, List<Pair<String, Int>>> = mapOf(
        Pair("'i've", "been") to listOf(Pair("thinking", 2)),
        Pair("--", "and") to listOf(Pair("that's", 2)),
        Pair("--", "i") to listOf(Pair("can", 3)),
        Pair("--", "it") to listOf(Pair("is", 8)),
        Pair("--", "it's") to listOf(Pair("about", 7), Pair("a", 5)),
        Pair("--", "not") to listOf(Pair("panicked,", 2)),
        Pair("--", "perfect") to listOf(Pair("conditions", 2)),
        Pair("--", "that's") to listOf(Pair("not", 3), Pair("your", 2)),
        Pair("--", "the") to listOf(Pair("oracle", 3)),
        Pair("--", "this") to listOf(Pair("is", 3), Pair("isn't", 2), Pair("question", 2)),
        Pair("--", "which") to listOf(Pair("is", 2)),
        Pair("--", "you") to listOf(Pair("are", 4)),
        Pair("--", "you're") to listOf(Pair("asking", 5), Pair("in", 3), Pair("not", 3), Pair("being", 2)),
        Pair("--", "you've") to listOf(Pair("been", 9)),
        Pair("--", "your") to listOf(Pair("body", 11), Pair("heart", 2)),
        Pair("about", "how") to listOf(Pair("you", 2)),
        Pair("about", "it") to listOf(Pair("--", 3)),
        Pair("about", "this") to listOf(Pair("--", 3)),
        Pair("access", "to") to listOf(Pair("your", 3)),
        Pair("active", "day") to listOf(Pair("prove", 2)),
        Pair("against", "the") to listOf(Pair("wrong", 2)),
        Pair("alert", "but") to listOf(Pair("not", 2)),
        Pair("all", "day") to listOf(Pair("--", 2)),
        Pair("all", "day,") to listOf(Pair("and", 2)),
        Pair("all", "storms") to listOf(Pair("either.", 2)),
        Pair("already", "know") to listOf(Pair("the", 2)),
        Pair("already", "suspect") to listOf(Pair("the", 2)),
        Pair("am,", "heart") to listOf(Pair("rate", 2)),
        Pair("am", "and") to listOf(Pair("your", 3)),
        Pair("am", "with") to listOf(Pair("a", 3)),
        Pair("and", "a") to listOf(Pair("heart", 9), Pair("calm", 4), Pair("steady", 2)),
        Pair("and", "active") to listOf(Pair("day", 3)),
        Pair("and", "bright") to listOf(Pair("morning", 2)),
        Pair("and", "dropping") to listOf(Pair("pressure", 3)),
        Pair("and", "i") to listOf(Pair("are", 2), Pair("can", 2), Pair("suspect", 2)),
        Pair("and", "people") to listOf(Pair("who", 2)),
        Pair("and", "right") to listOf(Pair("now,", 2)),
        Pair("and", "rising") to listOf(Pair("pressure", 5)),
        Pair("and", "stable") to listOf(Pair("pressure", 3), Pair("conditions", 3)),
        Pair("and", "the") to listOf(Pair("pressure", 8), Pair("morning", 4), Pair("sky", 3), Pair("oracle", 3), Pair("sun", 2), Pair("question", 2), Pair("best", 2)),
        Pair("and", "you") to listOf(Pair("already", 2)),
        Pair("and", "you're") to listOf(Pair("already", 3), Pair("asking", 2)),
        Pair("and", "your") to listOf(Pair("heart", 13), Pair("body", 3), Pair("tired", 2)),
        Pair("and", "yours") to listOf(Pair("is", 2)),
        Pair("answer", "is") to listOf(Pair("in", 3), Pair("not", 2)),
        Pair("are", "different") to listOf(Pair("things.", 2)),
        Pair("are", "the") to listOf(Pair("ones", 5)),
        Pair("are", "they") to listOf(Pair("offering", 2)),
        Pair("around", "you") to listOf(Pair("is", 2), Pair("suggests", 2), Pair("mirrors", 2), Pair("says", 2)),
        Pair("asking", "from") to listOf(Pair("a", 2)),
        Pair("asking", "tells") to listOf(Pair("me", 2)),
        Pair("asking", "the") to listOf(Pair("oracle", 2)),
        Pair("asking", "this") to listOf(Pair("from", 3)),
        Pair("asking", "whether") to listOf(Pair("you're", 2)),
        Pair("as", "much") to listOf(Pair("as", 4)),
        Pair("as", "though") to listOf(Pair("you", 2)),
        Pair("attention", "to") to listOf(Pair("what", 3)),
        Pair("at", "3") to listOf(Pair("am", 2), Pair("pm", 2)),
        Pair("at", "rest") to listOf(Pair("is", 2)),
        Pair("a", "calm") to listOf(Pair("heart", 2)),
        Pair("a", "difference") to listOf(Pair("between", 3)),
        Pair("a", "grounded") to listOf(Pair("place,", 2)),
        Pair("a", "heart") to listOf(Pair("rate", 21), Pair("that", 3), Pair("that's", 3)),
        Pair("a", "house") to listOf(Pair("is", 2)),
        Pair("a", "lot") to listOf(Pair("of", 2)),
        Pair("a", "moment") to listOf(Pair("of", 2)),
        Pair("a", "place") to listOf(Pair("of", 3)),
        Pair("a", "pulse") to listOf(Pair("of", 2)),
        Pair("a", "question") to listOf(Pair("for", 2)),
        Pair("a", "relationship") to listOf(Pair("that", 2)),
        Pair("a", "resting") to listOf(Pair("heart", 4)),
        Pair("beats", "per") to listOf(Pair("minute.", 2)),
        Pair("because", "you") to listOf(Pair("have", 2)),
        Pair("because", "your") to listOf(Pair("brain", 2)),
        Pair("been", "carrying") to listOf(Pair("this", 2)),
        Pair("been", "pacing") to listOf(Pair("through", 2)),
        Pair("been", "sitting") to listOf(Pair("with", 2)),
        Pair("been", "thinking") to listOf(Pair("about", 6)),
        Pair("before", "the") to listOf(Pair("storm", 2), Pair("day", 2)),
        Pair("body", "doesn't") to listOf(Pair("think", 2)),
        Pair("body", "has") to listOf(Pair("been", 2), Pair("already", 2)),
        Pair("body", "is") to listOf(Pair("telling", 5), Pair("in", 4), Pair("ready", 2)),
        Pair("bright", "morning") to listOf(Pair("and", 2)),
        Pair("build", "a") to listOf(Pair("life", 2)),
        Pair("but", "because") to listOf(Pair("your", 2)),
        Pair("but", "here's") to listOf(Pair("the", 3)),
        Pair("but", "i") to listOf(Pair("can", 4)),
        Pair("but", "i'll") to listOf(Pair("tell", 4)),
        Pair("but", "it's") to listOf(Pair("not", 2)),
        Pair("but", "only") to listOf(Pair("if", 2)),
        Pair("but", "the") to listOf(Pair("fact", 2)),
        Pair("but", "you") to listOf(Pair("can", 2)),
        Pair("calm", "afternoon") to listOf(Pair("state", 2)),
        Pair("calm", "enough") to listOf(Pair("to", 2)),
        Pair("calm", "evening") to listOf(Pair("pulse", 2)),
        Pair("calm", "heart") to listOf(Pair("rate", 3), Pair("--", 2)),
        Pair("calm", "night") to listOf(Pair("pulse", 2)),
        Pair("calm", "pulse") to listOf(Pair("says", 3), Pair("tells", 2)),
        Pair("can", "feel") to listOf(Pair("the", 5), Pair("it.", 2)),
        Pair("can", "tell") to listOf(Pair("you", 3)),
        Pair("care", "enough") to listOf(Pair("to", 2)),
        Pair("carry", "weight") to listOf(Pair("that", 2)),
        Pair("clarity,", "steady") to listOf(Pair("heart,", 2)),
        Pair("clarity", "tell") to listOf(Pair("me", 2)),
        Pair("closer", "to") to listOf(Pair("the", 2)),
        Pair("come", "to") to listOf(Pair("the", 3), Pair("me", 2)),
        Pair("conditions,", "and") to listOf(Pair("a", 3)),
        Pair("conditions", "are") to listOf(Pair("a", 2)),
        Pair("conditions", "tell") to listOf(Pair("me", 3)),
        Pair("couples", "therapy") to listOf(Pair("when", 2)),
        Pair("current", "situation") to listOf(Pair("is", 2)),
        Pair("day", "needs") to listOf(Pair("to", 2)),
        Pair("day", "tell") to listOf(Pair("me", 2)),
        Pair("did", "you") to listOf(Pair("need", 2)),
        Pair("don't", "have") to listOf(Pair("to", 4)),
        Pair("don't", "need") to listOf(Pair("to", 2)),
        Pair("don't", "owe") to listOf(Pair("anyone", 2)),
        Pair("do", "you") to listOf(Pair("miss", 2)),
        Pair("dropping", "around") to listOf(Pair("you.", 2)),
        Pair("dropping", "pressure") to listOf(Pair("says", 7), Pair("and", 2)),
        Pair("eight", "thousand") to listOf(Pair("steps", 2)),
        Pair("elevated", "heart") to listOf(Pair("rate", 4)),
        Pair("elevated", "pulse") to listOf(Pair("tells", 2)),
        Pair("eleven", "thousand") to listOf(Pair("steps", 4)),
        Pair("energy", "--") to listOf(Pair("you've", 2)),
        Pair("energy", "and") to listOf(Pair("rising", 2)),
        Pair("energy", "just") to listOf(Pair("to", 2)),
        Pair("energy", "to") to listOf(Pair("spare", 2)),
        Pair("evening", "energy") to listOf(Pair("and", 2)),
        Pair("evening", "tell") to listOf(Pair("me", 2)),
        Pair("even", "the") to listOf(Pair("oracle", 2)),
        Pair("everyone", "else") to listOf(Pair("is", 2)),
        Pair("every", "time") to listOf(Pair("you", 2)),
        Pair("excited", "about") to listOf(Pair("this", 2)),
        Pair("face", "to") to listOf(Pair("face,", 2)),
        Pair("fact", "that") to listOf(Pair("you're", 7), Pair("you", 3)),
        Pair("failure", "on") to listOf(Pair("something", 2)),
        Pair("feels", "like") to listOf(Pair("a", 4), Pair("the", 3)),
        Pair("feel", "like") to listOf(Pair("a", 3)),
        Pair("five", "hundred") to listOf(Pair("steps", 5)),
        Pair("for", "a") to listOf(Pair("long", 2)),
        Pair("for", "someone") to listOf(Pair("to", 2)),
        Pair("for", "the") to listOf(Pair("oracle", 2)),
        Pair("for", "two") to listOf(Pair("weeks.", 2)),
        Pair("for", "what") to listOf(Pair("you", 2)),
        Pair("from", "a") to listOf(Pair("place", 3), Pair("grounded", 3)),
        Pair("generosity", "that") to listOf(Pair("comes", 2)),
        Pair("give", "up") to listOf(Pair("on", 2)),
        Pair("going", "to") to listOf(Pair("therapy", 2)),
        Pair("good", "to") to listOf(Pair("be", 2)),
        Pair("go", "to") to listOf(Pair("sleep.", 2)),
        Pair("grounded", "place,") to listOf(Pair("not", 2)),
        Pair("haunt", "people") to listOf(Pair("who", 2)),
        Pair("have", "energy") to listOf(Pair("to", 2)),
        Pair("have", "the") to listOf(Pair("conversation", 2), Pair("patience", 2)),
        Pair("have", "this") to listOf(Pair("conversation", 2)),
        Pair("have", "to") to listOf(Pair("delete", 2)),
        Pair("have", "what") to listOf(Pair("it", 2)),
        Pair("have", "your") to listOf(Pair("answer.", 4)),
        Pair("heart", "--") to listOf(Pair("you're", 2)),
        Pair("heart", "is") to listOf(Pair("racing", 3), Pair("at", 3), Pair("steady,", 2), Pair("barely", 2), Pair("calm,", 2), Pair("running", 2), Pair("already", 2)),
        Pair("heart", "rate") to listOf(Pair("is", 23), Pair("of", 23), Pair("tells", 7), Pair("says", 4), Pair("at", 4), Pair("will", 4), Pair("and", 4), Pair("pushing", 2), Pair("bumped", 2), Pair("tell", 2)),
        Pair("heart", "says") to listOf(Pair("you're", 2)),
        Pair("heart", "tell") to listOf(Pair("me", 2)),
        Pair("here's", "how") to listOf(Pair("to", 3)),
        Pair("here's", "the") to listOf(Pair("oracle's", 7), Pair("truth:", 3)),
        Pair("here's", "what") to listOf(Pair("i", 4)),
        Pair("hundred", "steps") to listOf(Pair("on", 4), Pair("and", 2)),
        Pair("i'll", "tell") to listOf(Pair("you", 5)),
        Pair("if", "it") to listOf(Pair("feels", 2), Pair("sounds", 2)),
        Pair("if", "keeping") to listOf(Pair("it", 2)),
        Pair("if", "the") to listOf(Pair("thought", 2), Pair("world", 2), Pair("answer", 2)),
        Pair("if", "they") to listOf(Pair("don't,", 3)),
        Pair("if", "yes,") to listOf(Pair("it's", 2)),
        Pair("if", "you") to listOf(Pair("are", 3), Pair("can", 3), Pair("and", 2), Pair("need", 2), Pair("complain", 2)),
        Pair("if", "you're") to listOf(Pair("not", 2)),
        Pair("if", "your") to listOf(Pair("body", 2)),
        Pair("in", "a") to listOf(Pair("good", 2)),
        Pair("in", "the") to listOf(Pair("dark.", 4), Pair("quiet", 3), Pair("cool", 2), Pair("way", 2), Pair("dark", 2)),
        Pair("in", "your") to listOf(Pair("chest,", 2), Pair("chest", 2), Pair("mind.", 2), Pair("head.", 2)),
        Pair("isn't", "a") to listOf(Pair("panic", 2), Pair("crisis", 2), Pair("question", 2)),
        Pair("isn't", "about") to listOf(Pair("the", 2)),
        Pair("isn't", "an") to listOf(Pair("impulse.", 2)),
        Pair("isn't", "weakness") to listOf(Pair("--", 2)),
        Pair("isn't", "whether") to listOf(Pair("you", 2)),
        Pair("is", "a") to listOf(Pair("moment", 2)),
        Pair("is", "about") to listOf(Pair("to", 2)),
        Pair("is", "already") to listOf(Pair("at", 2)),
        Pair("is", "costing") to listOf(Pair("you", 3)),
        Pair("is", "dropping") to listOf(Pair("--", 2)),
        Pair("is", "elevated") to listOf(Pair("with", 2)),
        Pair("is", "falling") to listOf(Pair("--", 2)),
        Pair("is", "in") to listOf(Pair("your", 5), Pair("the", 3)),
        Pair("is", "meant") to listOf(Pair("to", 2)),
        Pair("is", "not") to listOf(Pair("a", 5), Pair("in", 2)),
        Pair("is", "one") to listOf(Pair("of", 2)),
        Pair("is", "ready") to listOf(Pair("for", 3)),
        Pair("is", "rising,") to listOf(Pair("which", 2)),
        Pair("is", "running") to listOf(Pair("hot", 3), Pair("a", 2)),
        Pair("is", "slightly") to listOf(Pair("elevated", 2)),
        Pair("is", "steady") to listOf(Pair("--", 2)),
        Pair("is", "steady,") to listOf(Pair("your", 2)),
        Pair("is", "telling") to listOf(Pair("you", 4), Pair("me", 2)),
        Pair("is", "the") to listOf(Pair("one", 5), Pair("only", 2), Pair("right", 2), Pair("sound", 2), Pair("perfect", 2)),
        Pair("is", "your") to listOf(Pair("body", 2), Pair("brain's", 2)),
        Pair("it's", "about") to listOf(Pair("deciding", 2), Pair("what", 2)),
        Pair("it's", "not") to listOf(Pair("a", 3), Pair("too", 2), Pair("always", 2), Pair("all", 2)),
        Pair("it's", "your") to listOf(Pair("mind", 2)),
        Pair("it", "--") to listOf(Pair("you've", 2), Pair("that's", 2)),
        Pair("it", "as") to listOf(Pair("a", 2)),
        Pair("it", "feels") to listOf(Pair("like", 2)),
        Pair("it", "is") to listOf(Pair("a", 2)),
        Pair("it", "makes") to listOf(Pair("your", 2)),
        Pair("it", "rewards") to listOf(Pair("the", 2)),
        Pair("it", "sounds") to listOf(Pair("like", 2)),
        Pair("it", "to") to listOf(Pair("yourself", 2)),
        Pair("it", "will") to listOf(Pair("not", 2)),
        Pair("i", "appreciate") to listOf(Pair("the", 2)),
        Pair("i", "can") to listOf(Pair("feel", 9), Pair("tell", 5), Pair("read", 2)),
        Pair("i", "hear") to listOf(Pair("you.", 3)),
        Pair("i", "know") to listOf(Pair("this", 2)),
        Pair("i", "suspect") to listOf(Pair("it", 2)),
        Pair("i", "want") to listOf(Pair("you", 2)),
        Pair("i", "will") to listOf(Pair("not", 2)),
        Pair("just", "looking") to listOf(Pair("for", 2)),
        Pair("just", "make") to listOf(Pair("sure", 2)),
        Pair("just", "thinking") to listOf(Pair("about", 3)),
        Pair("keeping", "it") to listOf(Pair("to", 2)),
        Pair("knows", "before") to listOf(Pair("your", 2)),
        Pair("know", "exactly") to listOf(Pair("what", 2)),
        Pair("know", "the") to listOf(Pair("answer.", 4)),
        Pair("know", "when") to listOf(Pair("to", 2)),
        Pair("know", "which") to listOf(Pair("one", 2)),
        Pair("letting", "go") to listOf(Pair("of", 2)),
        Pair("let", "it") to listOf(Pair("go.", 2)),
        Pair("light", "and") to listOf(Pair("a", 2)),
        Pair("like", "something") to listOf(Pair("you'd", 2)),
        Pair("listen", "to") to listOf(Pair("it.", 3)),
        Pair("loneliness", "is") to listOf(Pair("a", 2)),
        Pair("makes", "your") to listOf(Pair("pulse", 2)),
        Pair("making", "this") to listOf(Pair("decision", 2)),
        Pair("matters", "more") to listOf(Pair("than", 2)),
        Pair("matter", "to") to listOf(Pair("the", 3)),
        Pair("means", "part") to listOf(Pair("of", 2)),
        Pair("me", "conditions") to listOf(Pair("are", 2)),
        Pair("me", "more") to listOf(Pair("than", 3)),
        Pair("me", "this") to listOf(Pair("isn't", 9)),
        Pair("me", "you") to listOf(Pair("have", 8)),
        Pair("me", "you're") to listOf(Pair("not", 10), Pair("in", 2)),
        Pair("me", "you've") to listOf(Pair("been", 5), Pair("already", 3)),
        Pair("midday", "clarity,") to listOf(Pair("steady", 2)),
        Pair("mind", "refuses") to listOf(Pair("to", 2)),
        Pair("minutes", "a") to listOf(Pair("day.", 2)),
        Pair("mirrors", "the") to listOf(Pair("warmth", 2)),
        Pair("moderate", "steps,") to listOf(Pair("calm", 2)),
        Pair("more", "than") to listOf(Pair("your", 3)),
        Pair("morning,", "rising") to listOf(Pair("pressure,", 2)),
        Pair("morning", "--") to listOf(Pair("you're", 2)),
        Pair("morning", "and") to listOf(Pair("your", 2), Pair("rising", 2)),
        Pair("morning", "energy") to listOf(Pair("and", 2)),
        Pair("morning", "light") to listOf(Pair("and", 2)),
        Pair("morning", "pressure") to listOf(Pair("is", 5)),
        Pair("morning", "when") to listOf(Pair("your", 2)),
        Pair("moving", "home") to listOf(Pair("because", 2)),
        Pair("moving", "toward") to listOf(Pair("a", 2)),
        Pair("needs", "to") to listOf(Pair("be", 5)),
        Pair("need", "to") to listOf(Pair("say", 3)),
        Pair("nervous", "system") to listOf(Pair("knows", 2)),
        Pair("nine", "thousand") to listOf(Pair("steps", 5)),
        Pair("not", "a") to listOf(Pair("vacation", 2)),
        Pair("not", "all") to listOf(Pair("of", 2)),
        Pair("not", "because") to listOf(Pair("you're", 3), Pair("you", 2)),
        Pair("not", "during") to listOf(Pair("a", 2)),
        Pair("not", "in") to listOf(Pair("a", 2), Pair("the", 2), Pair("crisis.", 2), Pair("crisis", 2)),
        Pair("not", "just") to listOf(Pair("your", 2)),
        Pair("not", "too") to listOf(Pair("late.", 2)),
        Pair("now,", "your") to listOf(Pair("heart", 3)),
        Pair("no", "one") to listOf(Pair("else", 2)),
        Pair("of", "a") to listOf(Pair("heart", 2)),
        Pair("of", "it") to listOf(Pair("like", 2), Pair("--", 2)),
        Pair("of", "someone") to listOf(Pair("who", 3)),
        Pair("of", "the") to listOf(Pair("day", 2)),
        Pair("of", "trying") to listOf(Pair("to", 2)),
        Pair("of", "your") to listOf(Pair("life.", 2)),
        Pair("okay", "--") to listOf(Pair("it's", 2)),
        Pair("ones", "who") to listOf(Pair("stop", 2)),
        Pair("one", "of") to listOf(Pair("the", 2)),
        Pair("one", "thing") to listOf(Pair("you", 3)),
        Pair("one", "your") to listOf(Pair("body", 2)),
        Pair("only", "if") to listOf(Pair("you're", 2)),
        Pair("only", "way") to listOf(Pair("to", 2)),
        Pair("on", "a") to listOf(Pair("sunday", 2), Pair("saturday", 2)),
        Pair("on", "the") to listOf(Pair("other", 3)),
        Pair("on", "things") to listOf(Pair("that", 2)),
        Pair("oracle", "doesn't") to listOf(Pair("need", 2)),
        Pair("or", "away") to listOf(Pair("from", 2)),
        Pair("pacing", "through") to listOf(Pair("this", 2)),
        Pair("partly", "cloudy") to listOf(Pair("sky", 2)),
        Pair("part", "of") to listOf(Pair("this", 2), Pair("you", 2)),
        Pair("pay", "attention") to listOf(Pair("to", 3)),
        Pair("people", "who") to listOf(Pair("don't", 5), Pair("are", 3), Pair("truly", 2)),
        Pair("perfect", "conditions") to listOf(Pair("for", 2)),
        Pair("perfect", "state") to listOf(Pair("for", 3)),
        Pair("person", "on") to listOf(Pair("the", 2)),
        Pair("place,", "not") to listOf(Pair("a", 2)),
        Pair("pm", "on") to listOf(Pair("a", 2)),
        Pair("pressure,", "and") to listOf(Pair("a", 3)),
        Pair("pressure", "--") to listOf(Pair("you're", 2)),
        Pair("pressure", "and") to listOf(Pair("warm", 2)),
        Pair("pressure", "around") to listOf(Pair("you", 2)),
        Pair("pressure", "is") to listOf(Pair("dropping", 3), Pair("rising", 3), Pair("building", 2), Pair("rising,", 2), Pair("literally", 2)),
        Pair("pressure", "rising") to listOf(Pair("around", 3)),
        Pair("pressure", "say") to listOf(Pair("conditions", 3), Pair("you", 2), Pair("the", 2)),
        Pair("pressure", "says") to listOf(Pair("the", 5), Pair("change", 2), Pair("today", 2), Pair("conditions", 2), Pair("something", 2), Pair("your", 2), Pair("momentum", 2)),
        Pair("pulse", "--") to listOf(Pair("you're", 2)),
        Pair("pulse", "is") to listOf(Pair("elevated", 2)),
        Pair("pulse", "says") to listOf(Pair("you're", 3), Pair("this", 3)),
        Pair("pulse", "tells") to listOf(Pair("me", 6)),
        Pair("put", "it") to listOf(Pair("down.", 2)),
        Pair("put", "the") to listOf(Pair("phone", 2)),
        Pair("question", "for") to listOf(Pair("a", 2)),
        Pair("question", "has") to listOf(Pair("been", 2)),
        Pair("question", "is") to listOf(Pair("whether", 3)),
        Pair("question", "isn't") to listOf(Pair("whether", 2)),
        Pair("racing", "heart") to listOf(Pair("isn't", 2)),
        Pair("rate", "is") to listOf(Pair("at", 4), Pair("calm", 3), Pair("steady,", 2), Pair("slightly", 2), Pair("elevated", 2)),
        Pair("rate", "says") to listOf(Pair("you're", 3)),
        Pair("rate", "tell") to listOf(Pair("me", 2)),
        Pair("rate", "tells") to listOf(Pair("me", 7)),
        Pair("ready", "to") to listOf(Pair("stop", 2)),
        Pair("repeating", "the") to listOf(Pair("same", 2)),
        Pair("resting", "heart") to listOf(Pair("rate", 2), Pair("of", 2)),
        Pair("right", "now") to listOf(Pair("is", 2)),
        Pair("right", "now,") to listOf(Pair("your", 3)),
        Pair("right", "people") to listOf(Pair("will", 2)),
        Pair("rising", "around") to listOf(Pair("you", 3)),
        Pair("rising", "pressure") to listOf(Pair("says", 12), Pair("say", 5), Pair("and", 3)),
        Pair("rising", "pressure,") to listOf(Pair("and", 2)),
        Pair("running", "hot") to listOf(Pair("at", 2)),
        Pair("says", "change") to listOf(Pair("is", 2)),
        Pair("says", "momentum") to listOf(Pair("is", 3)),
        Pair("says", "something") to listOf(Pair("is", 2)),
        Pair("says", "the") to listOf(Pair("world", 2)),
        Pair("says", "this") to listOf(Pair("isn't", 2)),
        Pair("says", "today") to listOf(Pair("is", 2)),
        Pair("says", "you're") to listOf(Pair("not", 3), Pair("capable", 2)),
        Pair("says", "your") to listOf(Pair("current", 2)),
        Pair("say", "the") to listOf(Pair("conditions", 2)),
        Pair("say", "what") to listOf(Pair("you", 4)),
        Pair("say", "you") to listOf(Pair("have", 2)),
        Pair("say", "you've") to listOf(Pair("been", 2)),
        Pair("seek", "is") to listOf(Pair("already", 2)),
        Pair("shifting", "in") to listOf(Pair("your", 2)),
        Pair("show", "up") to listOf(Pair("in", 2)),
        Pair("sitting", "still") to listOf(Pair("--", 4), Pair("in", 2)),
        Pair("sitting", "with") to listOf(Pair("this", 2)),
        Pair("sixty", "beats") to listOf(Pair("per", 2)),
        Pair("sleep", "on") to listOf(Pair("it.", 2)),
        Pair("slightly", "elevated") to listOf(Pair("heart", 3), Pair("--", 2)),
        Pair("slight", "pressure") to listOf(Pair("drop", 4)),
        Pair("something,", "and") to listOf(Pair("the", 2)),
        Pair("something", "different") to listOf(Pair("--", 2)),
        Pair("something", "in") to listOf(Pair("your", 3)),
        Pair("something", "or") to listOf(Pair("away", 2)),
        Pair("some", "of") to listOf(Pair("that", 2)),
        Pair("sounds", "like") to listOf(Pair("something", 2)),
        Pair("sound", "of") to listOf(Pair("a", 2)),
        Pair("space", "in") to listOf(Pair("your", 2)),
        Pair("stable", "conditions") to listOf(Pair("tell", 2)),
        Pair("stable", "pressure") to listOf(Pair("say", 3)),
        Pair("stable", "pressure,") to listOf(Pair("and", 2)),
        Pair("state", "says") to listOf(Pair("you're", 2)),
        Pair("state", "tells") to listOf(Pair("me", 3)),
        Pair("steady,", "your") to listOf(Pair("body", 2)),
        Pair("steady", "--") to listOf(Pair("this", 2)),
        Pair("steady", "heart") to listOf(Pair("says", 2), Pair("rate", 2), Pair("tell", 2)),
        Pair("steady", "heart,") to listOf(Pair("and", 2)),
        Pair("steady", "pulse") to listOf(Pair("says", 2)),
        Pair("steps,", "heart") to listOf(Pair("rate", 2)),
        Pair("steps", "--") to listOf(Pair("you've", 2)),
        Pair("steps", "and") to listOf(Pair("a", 6), Pair("your", 2)),
        Pair("steps", "by") to listOf(Pair("late", 2)),
        Pair("steps", "of") to listOf(Pair("trying", 2)),
        Pair("steps", "on") to listOf(Pair("a", 5)),
        Pair("steps", "say") to listOf(Pair("you've", 2)),
        Pair("steps", "tell") to listOf(Pair("me", 2)),
        Pair("still", "--") to listOf(Pair("that's", 2)),
        Pair("suspect", "it") to listOf(Pair("wasn't", 2)),
        Pair("system", "knows") to listOf(Pair("before", 2)),
        Pair("take", "the") to listOf(Pair("leap.", 2)),
        Pair("telling", "you") to listOf(Pair("it's", 2), Pair("something.", 2)),
        Pair("tells", "me") to listOf(Pair("you're", 16), Pair("this", 11), Pair("you've", 7), Pair("you", 7), Pair("more", 3), Pair("everything.", 3), Pair("conditions", 2)),
        Pair("tell", "me") to listOf(Pair("you're", 8), Pair("you", 5), Pair("this", 4), Pair("you've", 2)),
        Pair("tell", "you") to listOf(Pair("what", 4), Pair("this:", 2), Pair("that", 2), Pair("which", 2)),
        Pair("ten", "thousand") to listOf(Pair("steps", 4)),
        Pair("than", "you") to listOf(Pair("think.", 2)),
        Pair("that's", "not") to listOf(Pair("love", 2)),
        Pair("that's", "the") to listOf(Pair("right", 2), Pair("only", 2)),
        Pair("that's", "your") to listOf(Pair("body", 3)),
        Pair("that", "comes") to listOf(Pair("from", 2)),
        Pair("that", "gives") to listOf(Pair("you", 2)),
        Pair("that", "lets") to listOf(Pair("you", 3)),
        Pair("that", "tells") to listOf(Pair("me", 3)),
        Pair("that", "you") to listOf(Pair("care", 3)),
        Pair("that", "you're") to listOf(Pair("asking", 3)),
        Pair("them", "with") to listOf(Pair("the", 2)),
        Pair("therapy", "when") to listOf(Pair("things", 2)),
        Pair("there's", "a") to listOf(Pair("difference", 3), Pair("difference.", 3)),
        Pair("there", "is") to listOf(Pair("no", 2)),
        Pair("they", "did") to listOf(Pair("was", 2)),
        Pair("the", "'yourself'") to listOf(Pair("you're", 2)),
        Pair("the", "act") to listOf(Pair("of", 2)),
        Pair("the", "answer") to listOf(Pair("is", 9), Pair("to", 3), Pair("you", 2)),
        Pair("the", "atmosphere") to listOf(Pair("is", 3)),
        Pair("the", "bright") to listOf(Pair("morning", 2)),
        Pair("the", "conditions") to listOf(Pair("are", 2)),
        Pair("the", "day") to listOf(Pair("has", 2)),
        Pair("the", "difference") to listOf(Pair("between", 2), Pair("is", 2)),
        Pair("the", "dropping") to listOf(Pair("pressure", 9)),
        Pair("the", "early") to listOf(Pair("morning", 2)),
        Pair("the", "fact") to listOf(Pair("that", 12)),
        Pair("the", "fix") to listOf(Pair("isn't", 2)),
        Pair("the", "gap") to listOf(Pair("between", 2)),
        Pair("the", "moment") to listOf(Pair("you", 2)),
        Pair("the", "morning") to listOf(Pair("pressure", 5)),
        Pair("the", "most") to listOf(Pair("productive", 2)),
        Pair("the", "one") to listOf(Pair("you", 3)),
        Pair("the", "ones") to listOf(Pair("who", 7)),
        Pair("the", "only") to listOf(Pair("way", 2)),
        Pair("the", "oracle") to listOf(Pair("has", 4), Pair("sees", 3), Pair("knows:", 3), Pair("doesn't", 2), Pair("says:", 2), Pair("can't", 2), Pair("about", 2)),
        Pair("the", "oracle's") to listOf(Pair("rule", 2)),
        Pair("the", "partly") to listOf(Pair("cloudy", 2)),
        Pair("the", "people") to listOf(Pair("who", 8)),
        Pair("the", "perfect") to listOf(Pair("state", 3)),
        Pair("the", "person") to listOf(Pair("who", 2)),
        Pair("the", "pressure") to listOf(Pair("is", 16), Pair("rising", 4), Pair("drops", 2)),
        Pair("the", "question") to listOf(Pair("is", 2), Pair("isn't", 2)),
        Pair("the", "real") to listOf(Pair("question", 2)),
        Pair("the", "relief") to listOf(Pair("will", 2)),
        Pair("the", "right") to listOf(Pair("one.", 3), Pair("people", 2)),
        Pair("the", "rising") to listOf(Pair("pressure", 17)),
        Pair("the", "sky") to listOf(Pair("is", 2)),
        Pair("the", "slight") to listOf(Pair("pressure", 3)),
        Pair("the", "sound") to listOf(Pair("of", 2)),
        Pair("the", "sun") to listOf(Pair("is", 2)),
        Pair("the", "thing") to listOf(Pair("you", 4), Pair("--", 2)),
        Pair("the", "thought") to listOf(Pair("of", 3)),
        Pair("the", "universe") to listOf(Pair("has", 2)),
        Pair("the", "version") to listOf(Pair("of", 2)),
        Pair("the", "warmth") to listOf(Pair("around", 2)),
        Pair("the", "way") to listOf(Pair("you", 2)),
        Pair("the", "window") to listOf(Pair("for", 2)),
        Pair("the", "world") to listOf(Pair("is", 4)),
        Pair("the", "worst") to listOf(Pair("that", 2)),
        Pair("things", "are") to listOf(Pair("in", 3)),
        Pair("things", "that") to listOf(Pair("drain", 2)),
        Pair("things", "you") to listOf(Pair("can", 2)),
        Pair("thing", "you") to listOf(Pair("keep", 2)),
        Pair("thinking", "about") to listOf(Pair("this.", 3), Pair("this", 3), Pair("it", 3)),
        Pair("think", "of") to listOf(Pair("it", 3)),
        Pair("this", "--") to listOf(Pair("you're", 2)),
        Pair("this", "from") to listOf(Pair("a", 3)),
        Pair("this", "is") to listOf(Pair("the", 5), Pair("a", 5), Pair("not", 2)),
        Pair("this", "isn't") to listOf(Pair("a", 12), Pair("an", 3), Pair("about", 2)),
        Pair("this", "question") to listOf(Pair("has", 3), Pair("for", 2), Pair("all", 2), Pair("a", 2), Pair("--", 2)),
        Pair("thousand", "five") to listOf(Pair("hundred", 5)),
        Pair("thousand", "steps") to listOf(Pair("of", 7), Pair("and", 6), Pair("by", 3), Pair("--", 2)),
        Pair("thousand", "steps,") to listOf(Pair("heart", 2)),
        Pair("times", "a") to listOf(Pair("minute,", 2)),
        Pair("time", "you") to listOf(Pair("do", 2)),
        Pair("today", "is") to listOf(Pair("the", 2)),
        Pair("too", "good") to listOf(Pair("to", 2)),
        Pair("too", "many") to listOf(Pair("seekers", 2)),
        Pair("toward", "clear") to listOf(Pair("skies.", 2)),
        Pair("toward", "something") to listOf(Pair("or", 2)),
        Pair("to", "be") to listOf(Pair("the", 2), Pair("a", 2), Pair("true", 2)),
        Pair("to", "build") to listOf(Pair("a", 2)),
        Pair("to", "the") to listOf(Pair("oracle", 5)),
        Pair("to", "this") to listOf(Pair("question", 2)),
        Pair("to", "who") to listOf(Pair("you", 2)),
        Pair("to", "your") to listOf(Pair("life,", 2)),
        Pair("to", "yourself") to listOf(Pair("feels", 2)),
        Pair("treat", "it") to listOf(Pair("like", 2)),
        Pair("up", "on") to listOf(Pair("the", 3)),
        Pair("up", "when") to listOf(Pair("you", 2)),
        Pair("version", "of") to listOf(Pair("you", 2)),
        Pair("waiting", "for") to listOf(Pair("someone", 2)),
        Pair("want", "you") to listOf(Pair("to", 2)),
        Pair("warmth", "around") to listOf(Pair("you", 2)),
        Pair("warm", "body") to listOf(Pair("and", 2)),
        Pair("weakness", "--") to listOf(Pair("it's", 2)),
        Pair("what", "i") to listOf(Pair("know:", 2)),
        Pair("what", "it") to listOf(Pair("is.", 3)),
        Pair("what", "makes") to listOf(Pair("you", 2)),
        Pair("what", "the") to listOf(Pair("oracle", 2)),
        Pair("what", "they") to listOf(Pair("did", 3)),
        Pair("what", "to") to listOf(Pair("do", 2)),
        Pair("what", "would") to listOf(Pair("you", 2)),
        Pair("what", "you") to listOf(Pair("need", 4), Pair("can", 3)),
        Pair("what", "you're") to listOf(Pair("feeling", 3)),
        Pair("what", "you've") to listOf(Pair("already", 2)),
        Pair("what", "your") to listOf(Pair("mind", 2)),
        Pair("when", "someone") to listOf(Pair("is", 2)),
        Pair("when", "things") to listOf(Pair("are", 2)),
        Pair("when", "you") to listOf(Pair("stop,", 2), Pair("didn't", 2), Pair("thought", 2)),
        Pair("when", "you're") to listOf(Pair("ready", 3)),
        Pair("when", "your") to listOf(Pair("pulse", 5), Pair("heart", 2)),
        Pair("where", "you") to listOf(Pair("stand.", 2)),
        Pair("whether", "it's") to listOf(Pair("a", 2)),
        Pair("whether", "you") to listOf(Pair("want", 2)),
        Pair("which", "means") to listOf(Pair("the", 3), Pair("your", 2)),
        Pair("which", "one") to listOf(Pair("your", 2)),
        Pair("which", "tells") to listOf(Pair("me", 4)),
        Pair("while", "sitting") to listOf(Pair("still", 4)),
        Pair("while", "you") to listOf(Pair("lie", 2)),
        Pair("while", "you're") to listOf(Pair("sitting", 2)),
        Pair("will", "not") to listOf(Pair("be", 2)),
        Pair("without", "you") to listOf(Pair("for", 2)),
        Pair("with", "a") to listOf(Pair("heart", 13), Pair("pulse", 3)),
        Pair("with", "the") to listOf(Pair("quiet", 2), Pair("same", 2)),
        Pair("with", "this") to listOf(Pair("question", 2)),
        Pair("won't", "be") to listOf(Pair("all", 2)),
        Pair("worst", "that") to listOf(Pair("happens", 2)),
        Pair("yes,", "take") to listOf(Pair("the", 2)),
        Pair("yes,", "tell") to listOf(Pair("them.", 2)),
        Pair("yes,", "you") to listOf(Pair("will", 2)),
        Pair("you're", "afraid") to listOf(Pair("to", 2), Pair("of", 2)),
        Pair("you're", "already") to listOf(Pair("moving", 2)),
        Pair("you're", "asking") to listOf(Pair("this", 5), Pair("the", 4), Pair("from", 3), Pair("tells", 2)),
        Pair("you're", "calm") to listOf(Pair("enough", 2)),
        Pair("you're", "capable") to listOf(Pair("of", 2)),
        Pair("you're", "doing") to listOf(Pair("too", 2)),
        Pair("you're", "in") to listOf(Pair("a", 4), Pair("the", 3)),
        Pair("you're", "just") to listOf(Pair("looking", 2)),
        Pair("you're", "not") to listOf(Pair("in", 5), Pair("angry", 2), Pair("being", 2)),
        Pair("you're", "ready") to listOf(Pair("to", 4)),
        Pair("you're", "running") to listOf(Pair("from", 2)),
        Pair("you're", "sitting") to listOf(Pair("still", 2)),
        Pair("you're", "strong") to listOf(Pair("enough", 2)),
        Pair("you've", "been") to listOf(Pair("thinking", 4), Pair("pacing", 2), Pair("sitting", 2), Pair("carrying", 2), Pair("running", 2), Pair("going", 2), Pair("busy", 2), Pair("building", 2)),
        Pair("you've", "done") to listOf(Pair("the", 2)),
        Pair("you've", "survived") to listOf(Pair("every", 3)),
        Pair("you,", "your") to listOf(Pair("nervous", 2)),
        Pair("yourself", "feels") to listOf(Pair("like", 2)),
        Pair("your", "body") to listOf(Pair("is", 29), Pair("has", 5), Pair("isn't", 4), Pair("already", 3), Pair("doesn't", 3), Pair("knows", 2)),
        Pair("your", "brain") to listOf(Pair("is", 3)),
        Pair("your", "calm") to listOf(Pair("pulse", 6), Pair("heart", 5), Pair("morning", 3), Pair("night", 2), Pair("afternoon", 2)),
        Pair("your", "conscious") to listOf(Pair("mind", 3)),
        Pair("your", "elevated") to listOf(Pair("pulse", 3)),
        Pair("your", "heart") to listOf(Pair("rate", 51), Pair("is", 25), Pair("beats", 4), Pair("needs", 2), Pair("will", 2)),
        Pair("your", "morning") to listOf(Pair("energy", 2)),
        Pair("your", "nervous") to listOf(Pair("system", 7)),
        Pair("your", "pulse") to listOf(Pair("is", 9)),
        Pair("your", "question") to listOf(Pair("with", 2)),
        Pair("your", "racing") to listOf(Pair("heart", 3)),
        Pair("your", "slightly") to listOf(Pair("elevated", 2)),
        Pair("your", "stable") to listOf(Pair("pressure", 2)),
        Pair("your", "steady") to listOf(Pair("heart", 6), Pair("pulse", 3), Pair("evening", 2)),
        Pair("your", "warm") to listOf(Pair("body", 2), Pair("evening", 2)),
        Pair("you", "already") to listOf(Pair("know", 4), Pair("suspect", 3)),
        Pair("you", "always") to listOf(Pair("were.", 2)),
        Pair("you", "are") to listOf(Pair("not", 7), Pair("a", 4), Pair("literally", 2), Pair("in", 2), Pair("enough.", 2)),
        Pair("you", "ask") to listOf(Pair("about", 3)),
        Pair("you", "asked") to listOf(Pair("--", 2)),
        Pair("you", "can") to listOf(Pair("afford", 3)),
        Pair("you", "care") to listOf(Pair("about", 2), Pair("enough", 2)),
        Pair("you", "come") to listOf(Pair("to", 4)),
        Pair("you", "complain") to listOf(Pair("about", 3)),
        Pair("you", "don't") to listOf(Pair("have", 4), Pair("owe", 2), Pair("need", 2)),
        Pair("you", "energy") to listOf(Pair("just", 2)),
        Pair("you", "have") to listOf(Pair("the", 8), Pair("your", 4), Pair("been", 3), Pair("energy", 3), Pair("it.", 2), Pair("stability", 2)),
        Pair("you", "know") to listOf(Pair("the", 3), Pair("what", 2), Pair("exactly", 2)),
        Pair("you", "matter") to listOf(Pair("to", 3)),
        Pair("you", "mirrors") to listOf(Pair("the", 2)),
        Pair("you", "miss") to listOf(Pair("the", 2)),
        Pair("you", "more") to listOf(Pair("than", 2)),
        Pair("you", "need") to listOf(Pair("to", 4), Pair("to.", 2)),
        Pair("you", "of") to listOf(Pair("a", 2)),
        Pair("you", "pulled") to listOf(Pair("back", 2)),
        Pair("you", "seek") to listOf(Pair("is", 2)),
        Pair("you", "to") to listOf(Pair("know:", 2)),
        Pair("you", "used") to listOf(Pair("to", 2)),
        Pair("you", "wait") to listOf(Pair("for", 3)),
        Pair("you", "want") to listOf(Pair("to", 3), Pair("to.", 2)),
        Pair("you", "what") to listOf(Pair("your", 2)),
        Pair("you", "will") to listOf(Pair("be", 2)),
    )

    private val starterBigrams: List<Pair<Pair<String, String>, Int>> = listOf(
        Pair(Pair("your", "heart"), 59),
        Pair(Pair("your", "body"), 32),
        Pair(Pair("your", "calm"), 30),
        Pair(Pair("you", "are"), 22),
        Pair(Pair("your", "steady"), 17),
        Pair(Pair("the", "rising"), 15),
        Pair(Pair("the", "answer"), 14),
        Pair(Pair("if", "it"), 14),
        Pair(Pair("if", "you"), 13),
        Pair(Pair("here's", "the"), 13),
        Pair(Pair("the", "oracle"), 12),
        Pair(Pair("you've", "been"), 12),
        Pair(Pair("you're", "not"), 11),
        Pair(Pair("the", "pressure"), 11),
        Pair(Pair("this", "is"), 10),
        Pair(Pair("not", "because"), 10),
        Pair(Pair("if", "the"), 10),
        Pair(Pair("the", "fact"), 9),
        Pair(Pair("you", "don't"), 9),
        Pair(Pair("there's", "a"), 9),
        Pair(Pair("the", "dropping"), 9),
        Pair(Pair("heart", "rate"), 9),
        Pair(Pair("you", "have"), 8),
        Pair(Pair("not", "every"), 8),
        Pair(Pair("your", "pulse"), 7),
        Pair(Pair("it's", "not"), 7),
        Pair(Pair("if", "they"), 7),
        Pair(Pair("you", "know"), 6),
        Pair(Pair("that's", "the"), 6),
        Pair(Pair("that's", "a"), 6),
        Pair(Pair("not", "a"), 6),
        Pair(Pair("right", "now,"), 6),
        Pair(Pair("the", "people"), 6),
        Pair(Pair("your", "stable"), 6),
        Pair(Pair("you", "can"), 6),
        Pair(Pair("this", "isn't"), 5),
        Pair(Pair("here's", "what"), 5),
        Pair(Pair("if", "it's"), 5),
        Pair(Pair("if", "you're"), 5),
        Pair(Pair("and", "the"), 5),
        Pair(Pair("it's", "a"), 5),
        Pair(Pair("nine", "thousand"), 5),
        Pair(Pair("i", "can"), 5),
        Pair(Pair("a", "heart"), 5),
        Pair(Pair("the", "atmosphere"), 4),
        Pair(Pair("what", "you"), 4),
        Pair(Pair("take", "the"), 4),
        Pair(Pair("wait", "until"), 4),
        Pair(Pair("but", "the"), 4),
        Pair(Pair("and", "you"), 4),
        Pair(Pair("people", "who"), 4),
        Pair(Pair("yes,", "you"), 4),
        Pair(Pair("that's", "not"), 4),
        Pair(Pair("the", "worst"), 4),
        Pair(Pair("trust", "that"), 4),
        Pair(Pair("you", "can't"), 4),
        Pair(Pair("i", "hear"), 4),
        Pair(Pair("the", "question"), 4),
        Pair(Pair("but", "i'll"), 4),
        Pair(Pair("if", "your"), 4),
        Pair(Pair("the", "best"), 4),
        Pair(Pair("ten", "thousand"), 4),
        Pair(Pair("here's", "how"), 4),
        Pair(Pair("eleven", "thousand"), 4),
        Pair(Pair("you're", "asking"), 4),
        Pair(Pair("your", "warm"), 4),
        Pair(Pair("say", "what"), 4),
        Pair(Pair("but", "not"), 4),
        Pair(Pair("in", "the"), 3),
        Pair(Pair("yes", "--"), 3),
        Pair(Pair("you", "come"), 3),
        Pair(Pair("the", "universe"), 3),
        Pair(Pair("the", "night"), 3),
        Pair(Pair("you", "already"), 3),
        Pair(Pair("you", "will"), 3),
        Pair(Pair("the", "morning"), 3),
        Pair(Pair("but", "i"), 3),
        Pair(Pair("the", "only"), 3),
        Pair(Pair("the", "thing"), 3),
        Pair(Pair("when", "someone"), 3),
        Pair(Pair("i", "won't"), 3),
        Pair(Pair("pay", "attention"), 3),
        Pair(Pair("yes,", "you're"), 3),
        Pair(Pair("you", "always"), 3),
        Pair(Pair("your", "elevated"), 3),
        Pair(Pair("but", "here's"), 3),
        Pair(Pair("when", "you're"), 3),
        Pair(Pair("let", "it"), 3),
        Pair(Pair("it's", "the"), 3),
        Pair(Pair("it's", "about"), 3),
        Pair(Pair("you're", "already"), 3),
        Pair(Pair("if", "this"), 3),
        Pair(Pair("there", "is"), 3),
        Pair(Pair("it", "always"), 3),
        Pair(Pair("twelve", "thousand"), 3),
        Pair(Pair("find", "someone"), 3),
        Pair(Pair("think", "of"), 3),
        Pair(Pair("you're", "in"), 3),
        Pair(Pair("not", "to"), 3),
        Pair(Pair("make", "the"), 3),
        Pair(Pair("whether", "it's"), 3),
        Pair(Pair("eight", "thousand"), 3),
        Pair(Pair("thirteen", "thousand"), 3),
        Pair(Pair("start", "by"), 3),
        Pair(Pair("the", "slight"), 3),
        Pair(Pair("your", "morning"), 3),
        Pair(Pair("not", "the"), 3),
        Pair(Pair("yes,", "take"), 3),
        Pair(Pair("the", "warm"), 3),
        Pair(Pair("you", "didn't"), 3),
        Pair(Pair("if", "yes,"), 3),
        Pair(Pair("here's", "my"), 3),
        Pair(Pair("make", "it"), 3),
        Pair(Pair("what", "would"), 3),
        Pair(Pair("start", "with"), 3),
        Pair(Pair("say", "it"), 3),
        Pair(Pair("your", "quiet"), 3),
        Pair(Pair("the", "difference"), 3),
        Pair(Pair("your", "gut"), 3),
        Pair(Pair("the", "darkness"), 2),
        Pair(Pair("in", "this"), 2),
        Pair(Pair("follow", "it"), 2),
        Pair(Pair("honor", "that"), 2),
        Pair(Pair("i", "will"), 2),
        Pair(Pair("when", "you"), 2),
        Pair(Pair("listen", "to"), 2),
        Pair(Pair("the", "evening"), 2),
        Pair(Pair("but", "it"), 2),
        Pair(Pair("it", "is"), 2),
        Pair(Pair("sixty", "beats"), 2),
        Pair(Pair("letting", "go"), 2),
        Pair(Pair("when", "your"), 2),
        Pair(Pair("put", "the"), 2),
        Pair(Pair("yes,", "ask"), 2),
        Pair(Pair("you've", "already"), 2),
        Pair(Pair("something", "has"), 2),
        Pair(Pair("pick", "the"), 2),
        Pair(Pair("better", "to"), 2),
        Pair(Pair("and", "you're"), 2),
        Pair(Pair("look", "at"), 2),
        Pair(Pair("sometimes", "it's"), 2),
        Pair(Pair("it's", "2"), 2),
        Pair(Pair("and", "your"), 2),
        Pair(Pair("most", "people"), 2),
        Pair(Pair("go", "to"), 2),
        Pair(Pair("let", "the"), 2),
        Pair(Pair("it's", "late,"), 2),
        Pair(Pair("your", "mind"), 2),
        Pair(Pair("yes,", "it's"), 2),
        Pair(Pair("the", "truth"), 2),
        Pair(Pair("i'll", "be"), 2),
        Pair(Pair("four", "thousand"), 2),
        Pair(Pair("only", "you"), 2),
        Pair(Pair("the", "relief"), 2),
        Pair(Pair("your", "slightly"), 2),
        Pair(Pair("here's", "a"), 2),
        Pair(Pair("that", "tells"), 2),
        Pair(Pair("that's", "your"), 2),
        Pair(Pair("yes,", "go"), 2),
        Pair(Pair("midnight,", "heart"), 2),
        Pair(Pair("i", "know"), 2),
        Pair(Pair("yes,", "tell"), 2),
        Pair(Pair("tell", "them"), 2),
        Pair(Pair("not", "during"), 2),
        Pair(Pair("whatever", "you"), 2),
        Pair(Pair("sleep", "on"), 2),
        Pair(Pair("now", "stop"), 2),
        Pair(Pair("something", "in"), 2),
        Pair(Pair("change", "one"), 2),
        Pair(Pair("everyone", "else"), 2),
        Pair(Pair("your", "racing"), 2),
        Pair(Pair("put", "it"), 2),
        Pair(Pair("midday", "clarity,"), 2),
        Pair(Pair("it's", "your"), 2),
        Pair(Pair("give", "it"), 2),
        Pair(Pair("morning", "energy,"), 2),
        Pair(Pair("don't", "overthink"), 2),
        Pair(Pair("not", "for"), 2),
        Pair(Pair("the", "version"), 2),
        Pair(Pair("yes,", "write"), 2),
        Pair(Pair("but", "because"), 2),
        Pair(Pair("if", "no,"), 2),
        Pair(Pair("just", "make"), 2),
        Pair(Pair("a", "resting"), 2),
        Pair(Pair("some", "of"), 2),
        Pair(Pair("set", "a"), 2),
        Pair(Pair("the", "kind"), 2),
        Pair(Pair("whatever", "you'd"), 2),
        Pair(Pair("it's", "whether"), 2),
        Pair(Pair("the", "fix"), 2),
        Pair(Pair("you", "matter"), 2),
        Pair(Pair("yes,", "and"), 2),
        Pair(Pair("learn", "to"), 2),
        Pair(Pair("it", "means"), 2),
        Pair(Pair("the", "warmth"), 2),
        Pair(Pair("they", "don't"), 2),
        Pair(Pair("you're", "exactly"), 2),
        Pair(Pair("the", "partly"), 2),
        Pair(Pair("friday", "evening,"), 2),
        Pair(Pair("a", "house"), 2),
        Pair(Pair("late", "night,"), 2),
        Pair(Pair("moving", "home"), 2),
        Pair(Pair("let", "your"), 2),
        Pair(Pair("if", "that's"), 2),
        Pair(Pair("write", "it"), 2),
        Pair(Pair("the", "act"), 2),
        Pair(Pair("there's", "no"), 2),
        Pair(Pair("the", "right"), 2),
        Pair(Pair("yes,", "learn"), 2),
        Pair(Pair("what", "you're"), 2),
        Pair(Pair("the", "rest"), 2),
        Pair(Pair("that's", "always"), 2),
        Pair(Pair("read", "the"), 2),
        Pair(Pair("check", "the"), 2),
        Pair(Pair("save", "the"), 2),
        Pair(Pair("clear", "morning,"), 2),
        Pair(Pair("choose", "a"), 2),
        Pair(Pair("come", "back"), 2),
        Pair(Pair("generosity", "that"), 2),
        Pair(Pair("vulnerability", "is"), 2),
        Pair(Pair("but", "don't"), 2),
        Pair(Pair("couples", "therapy"), 2),
        Pair(Pair("yes,", "try"), 2),
        Pair(Pair("going", "to"), 2),
        Pair(Pair("ask", "yourself:"), 2),
        Pair(Pair("the", "bright"), 2),
        Pair(Pair("see", "them"), 2),
        Pair(Pair("this", "one"), 2),
        Pair(Pair("if", "keeping"), 2),
    )

    private val categoryStarters: Map<String, List<Pair<Pair<String, String>, Int>>> = mapOf(
        "CAREER" to listOf(
            Pair(Pair("your", "heart"), 7),
            Pair(Pair("your", "pulse"), 3),
            Pair(Pair("if", "you"), 3),
            Pair(Pair("you've", "been"), 2),
            Pair(Pair("here's", "a"), 2),
            Pair(Pair("if", "it's"), 2),
            Pair(Pair("here's", "the"), 2),
            Pair(Pair("if", "they"), 2),
            Pair(Pair("your", "blood"), 1),
            Pair(Pair("fortune", "favors"), 1),
            Pair(Pair("the", "wealth"), 1),
            Pair(Pair("your", "body"), 1),
            Pair(Pair("the", "earth's"), 1),
            Pair(Pair("your", "career"), 1),
            Pair(Pair("follow", "it"), 1),
            Pair(Pair("the", "magnetic"), 1),
            Pair(Pair("when", "your"), 1),
            Pair(Pair("the", "excitement"), 1),
            Pair(Pair("take", "the"), 1),
            Pair(Pair("this", "isn't"), 1),
            Pair(Pair("this", "is"), 1),
            Pair(Pair("when", "the"), 1),
            Pair(Pair("start", "planning"), 1),
            Pair(Pair("you've", "already"), 1),
            Pair(Pair("invest,", "but"), 1),
            Pair(Pair("your", "body's"), 1),
            Pair(Pair("put", "in"), 1),
            Pair(Pair("patience", "builds"), 1),
            Pair(Pair("rising", "pressure"), 1),
            Pair(Pair("yes,", "start"), 1),
        ),
        "FEAR" to listOf(
            Pair(Pair("your", "heart"), 1),
            Pair(Pair("i", "will"), 1),
            Pair(Pair("but", "worry"), 1),
            Pair(Pair("the", "alarm"), 1),
            Pair(Pair("thirteen", "thousand"), 1),
            Pair(Pair("you", "can"), 1),
            Pair(Pair("yes,", "confront"), 1),
            Pair(Pair("not", "because"), 1),
            Pair(Pair("but", "because"), 1),
            Pair(Pair("it's", "taking"), 1),
            Pair(Pair("your", "warm"), 1),
            Pair(Pair("walk", "straight"), 1),
        ),
        "GENERAL" to listOf(
            Pair(Pair("your", "heart"), 48),
            Pair(Pair("your", "calm"), 29),
            Pair(Pair("your", "body"), 22),
            Pair(Pair("you", "are"), 21),
            Pair(Pair("your", "steady"), 16),
            Pair(Pair("the", "rising"), 15),
            Pair(Pair("if", "it"), 14),
            Pair(Pair("the", "answer"), 12),
            Pair(Pair("the", "oracle"), 11),
            Pair(Pair("the", "pressure"), 11),
            Pair(Pair("here's", "the"), 10),
            Pair(Pair("the", "fact"), 9),
            Pair(Pair("if", "you"), 9),
            Pair(Pair("you're", "not"), 9),
            Pair(Pair("you", "don't"), 9),
            Pair(Pair("not", "because"), 9),
            Pair(Pair("you've", "been"), 9),
            Pair(Pair("if", "the"), 9),
            Pair(Pair("you", "have"), 8),
            Pair(Pair("this", "is"), 8),
            Pair(Pair("there's", "a"), 8),
            Pair(Pair("the", "dropping"), 8),
            Pair(Pair("not", "every"), 7),
            Pair(Pair("heart", "rate"), 7),
            Pair(Pair("right", "now,"), 6),
            Pair(Pair("the", "people"), 6),
            Pair(Pair("your", "stable"), 6),
            Pair(Pair("that's", "the"), 5),
            Pair(Pair("if", "they"), 5),
            Pair(Pair("it's", "a"), 5),
        ),
        "HEALTH" to listOf(
            Pair(Pair("your", "body"), 6),
            Pair(Pair("this", "is"), 1),
            Pair(Pair("continue", "the"), 1),
            Pair(Pair("you", "know"), 1),
            Pair(Pair("soon", "it"), 1),
            Pair(Pair("your", "heart"), 1),
            Pair(Pair("that's", "your"), 1),
            Pair(Pair("when", "your"), 1),
            Pair(Pair("yes,", "go"), 1),
            Pair(Pair("not", "to"), 1),
            Pair(Pair("catching", "things"), 1),
            Pair(Pair("make", "the"), 1),
            Pair(Pair("heart", "rate"), 1),
            Pair(Pair("here's", "the"), 1),
            Pair(Pair("it's", "not"), 1),
            Pair(Pair("but", "when"), 1),
            Pair(Pair("bring", "them"), 1),
            Pair(Pair("but", "don't"), 1),
            Pair(Pair("add", "one"), 1),
            Pair(Pair("drink", "one"), 1),
            Pair(Pair("grand", "dietary"), 1),
            Pair(Pair("small", "daily"), 1),
            Pair(Pair("it", "needs"), 1),
        ),
        "RELATIONSHIP" to listOf(
            Pair(Pair("your", "heart"), 2),
            Pair(Pair("the", "invisible"), 1),
            Pair(Pair("like", "the"), 1),
            Pair(Pair("wait", "until"), 1),
            Pair(Pair("clarity", "cannot"), 1),
            Pair(Pair("your", "gentle"), 1),
            Pair(Pair("love", "does"), 1),
            Pair(Pair("you", "are"), 1),
            Pair(Pair("the", "answer"), 1),
            Pair(Pair("morning", "clarity,"), 1),
            Pair(Pair("that's", "a"), 1),
            Pair(Pair("yes,", "say"), 1),
            Pair(Pair("not", "every"), 1),
            Pair(Pair("sometimes", "it's"), 1),
            Pair(Pair("your", "body"), 1),
            Pair(Pair("go", "enjoy"), 1),
            Pair(Pair("it's", "2"), 1),
            Pair(Pair("i", "hear"), 1),
            Pair(Pair("the", "loneliness"), 1),
            Pair(Pair("your", "elevated"), 1),
            Pair(Pair("it's", "not"), 1),
            Pair(Pair("and", "your"), 1),
            Pair(Pair("your", "pulse"), 1),
            Pair(Pair("a", "business"), 1),
            Pair(Pair("but", "excitement"), 1),
            Pair(Pair("the", "oracle"), 1),
            Pair(Pair("let", "the"), 1),
            Pair(Pair("it's", "late,"), 1),
            Pair(Pair("that's", "not"), 1),
            Pair(Pair("a", "relationship"), 1),
        ),
        "TIMING" to listOf(
            Pair(Pair("there", "is"), 2),
            Pair(Pair("your", "body"), 2),
            Pair(Pair("the", "sky"), 1),
            Pair(Pair("the", "timing"), 1),
            Pair(Pair("but", "the"), 1),
            Pair(Pair("act", "now"), 1),
            Pair(Pair("you're", "awake"), 1),
            Pair(Pair("yes", "--"), 1),
            Pair(Pair("but", "good"), 1),
            Pair(Pair("you've", "already"), 1),
            Pair(Pair("now", "go"), 1),
            Pair(Pair("morning", "light,"), 1),
            Pair(Pair("your", "steady"), 1),
            Pair(Pair("if", "you"), 1),
            Pair(Pair("it", "always"), 1),
            Pair(Pair("morning", "energy,"), 1),
            Pair(Pair("yes,", "today"), 1),
            Pair(Pair("but", "let"), 1),
            Pair(Pair("start", "a"), 1),
            Pair(Pair("treat", "it"), 1),
            Pair(Pair("small", "changes,"), 1),
            Pair(Pair("it's", "sunday"), 1),
            Pair(Pair("and", "the"), 1),
            Pair(Pair("productivity", "is"), 1),
            Pair(Pair("you've", "been"), 1),
            Pair(Pair("not", "lazy"), 1),
            Pair(Pair("the", "kind"), 1),
            Pair(Pair("you've", "earned"), 1),
            Pair(Pair("clear", "morning,"), 1),
            Pair(Pair("yes,", "it's"), 1),
        ),
    )

    private val fallbackResponses: List<String> = listOf(
        "I feel the thunder of your pulse echoing through the void.",
        "When you are ready to voice what truly haunts you, return.",
        "You come to the Oracle mid-stride, blood pumping, muscles burning, sweat marking your devotion to motion.",
        "That's the perfect state for beginning something new.",
        "I'm not saying leave tonight.",
        "The dropping pressure says change is coming regardless.",
        "Count to four in, hold for four, out for six.",
        "The universe reveals its plans only to those in motion.",
        "There's a difference, and I can feel it.",
        "And if not, at least you showed up.",
        "Your pulse bumped just asking me -- that's your body bracing for impact.",
        "If you complain about being tired, go to bed earlier.",
        "You just haven't named it yet.",
        "Your cool afternoon calm is the perfect state for honest words.",
        "Trust what feels obvious -- the universe has no riddle for you today.",
        "The morning pressure is rising -- conditions favor truth today.",
        "The answer you seek is already written in your heart.",
        "Tell them tomorrow, in person, when you can see their face.",
        "Going to therapy is one of the most productive things a self-aware person can do.",
        "Sadness doesn't always need a reason.",
    )

    // Common verbs for quality filtering
    private val commonVerbs: Set<String> = setOf(
        "is", "are", "was", "were", "be", "been", "being",
        "have", "has", "had", "do", "does", "did", "done",
        "will", "would", "could", "should", "can", "may", "might",
        "shall", "must", "need", "dare",
        "go", "goes", "went", "gone", "going",
        "come", "comes", "came", "coming",
        "take", "takes", "took", "taken", "taking",
        "make", "makes", "made", "making",
        "know", "knows", "knew", "known", "knowing",
        "think", "thinks", "thought", "thinking",
        "see", "sees", "saw", "seen", "seeing",
        "want", "wants", "wanted", "wanting",
        "give", "gives", "gave", "given", "giving",
        "tell", "tells", "told", "telling",
        "say", "says", "said", "saying",
        "get", "gets", "got", "getting",
        "find", "finds", "found", "finding",
        "feel", "feels", "felt", "feeling",
        "try", "tries", "tried", "trying",
        "leave", "leaves", "left", "leaving",
        "call", "calls", "called", "calling",
        "keep", "keeps", "kept", "keeping",
        "let", "lets", "letting",
        "begin", "begins", "began", "beginning",
        "show", "shows", "showed", "shown", "showing",
        "hear", "hears", "heard", "hearing",
        "run", "runs", "ran", "running",
        "move", "moves", "moved", "moving",
        "live", "lives", "lived", "living",
        "believe", "believes", "believed",
        "hold", "holds", "held", "holding",
        "bring", "brings", "brought",
        "happen", "happens", "happened",
        "reach", "reaches", "reached",
        "stay", "stays", "stayed", "staying",
        "start", "starts", "started", "starting",
        "stop", "stops", "stopped", "stopping",
        "trust", "trusts", "trusted",
        "seek", "seeks", "sought",
        "ask", "asks", "asked", "asking",
        "listen", "listens", "listened",
        "follow", "follows", "followed",
        "learn", "learns", "learned",
        "change", "changes", "changed",
        "build", "builds", "built",
        "burn", "burns", "burned",
        "carry", "carries", "carried",
        "stand", "stands", "stood", "standing",
        "sit", "sits", "sat", "sitting",
        "speak", "speaks", "spoke", "spoken",
        "read", "reads", "reading",
        "grow", "grows", "grew", "growing",
        "turn", "turns", "turned", "turning",
        "walk", "walks", "walked", "walking",
        "pay", "pays", "paid",
        "meet", "meets", "met",
        "send", "sends", "sent",
        "fall", "falls", "fell", "fallen",
        "wait", "waits", "waited", "waiting",
        "accept", "accepts", "accepted",
        "expect", "expects", "expected",
        "remember", "remembers", "remembered",
        "serve", "serves", "served",
        "appear", "appears", "appeared",
        "die", "dies", "died",
        "miss", "misses", "missed",
        "rest", "rests", "rested", "resting",
        "wake", "wakes", "woke",
        "open", "opens", "opened",
        "close", "closes", "closed",
        "win", "wins", "won",
        "lose", "loses", "lost",
        "prepare", "prepares", "prepared",
        "require", "requires", "required",
        "fear", "fears", "feared",
        "break", "breaks", "broke", "broken",
        "catch", "catches", "caught",
        "pull", "pulls", "pulled",
        "set", "sets", "setting",
        "put", "puts", "putting",
        "pass", "passes", "passed",
        "step", "steps", "stepped",
        "race", "races", "raced", "racing",
        "beat", "beats", "beating",
        "whisper", "whispers", "whispered",
        "honor", "honors", "honored",
        "invest", "invests", "invested",
        "decide", "decides", "decided",
        "act", "acts", "acted",
        "respond", "responds", "responded",
        "protect", "protects", "protected",
        "notice", "notices", "noticed",
        "measure", "measures", "measured",
        "settle", "settles", "settled",
        "matters", "counts", "helps", "hurts",
        "exists", "means", "works", "needs"
    )

    private fun mapCategoryToKey(category: QuestionCategory?): String {
        return when (category) {
            QuestionCategory.RELATIONSHIP -> "RELATIONSHIP"
            QuestionCategory.CAREER -> "CAREER"
            QuestionCategory.HEALTH -> "HEALTH"
            QuestionCategory.TIMING -> "TIMING"
            QuestionCategory.FEAR -> "FEAR"
            QuestionCategory.YES_NO -> "GENERAL"
            QuestionCategory.GENERAL -> "GENERAL"
            null -> "GENERAL"
        }
    }

    /**
     * Pick a starter bigram, preferring ones relevant to the given category.
     */
    private fun pickStarter(category: QuestionCategory?): Pair<String, String> {
        val catKey = mapCategoryToKey(category)
        val candidates = categoryStarters[catKey] ?: starterBigrams

        if (candidates.isEmpty()) {
            val idx = random.nextInt(starterBigrams.size)
            return starterBigrams[idx].first
        }

        val totalWeight = candidates.sumOf { it.second }
        var roll = random.nextInt(totalWeight)
        for ((bigram, weight) in candidates) {
            roll -= weight
            if (roll < 0) return bigram
        }
        return candidates.last().first
    }

    /**
     * Sample the next word from the transition distribution, applying temperature.
     */
    private fun sampleNext(current: Pair<String, String>): String? {
        val options = transitions[current] ?: return null
        if (options.isEmpty()) return null

        if (temperature <= 0.01) {
            // Greedy: pick highest frequency
            return options.maxBy { it.second }.first
        }

        // Apply temperature scaling
        val weights = if (temperature == 1.0) {
            options.map { it.second.toDouble() }
        } else {
            val maxW = options.maxOf { it.second }.toDouble()
            options.map { Math.pow(it.second.toDouble() / maxW, 1.0 / temperature) }
        }

        val totalWeight = weights.sum()
        var roll = random.nextDouble() * totalWeight
        for (i in options.indices) {
            roll -= weights[i]
            if (roll <= 0) return options[i].first
        }
        return options.last().first
    }

    /**
     * Check if generated text contains at least one verb (quality filter).
     */
    private fun containsVerb(words: List<String>): Boolean {
        return words.any { word ->
            val cleaned = word.lowercase().trimEnd('.', ',', '!', '?', ';', ':')
            cleaned in commonVerbs
        }
    }

    /**
     * Post-process generated text: capitalize first letter, ensure ending punctuation.
     */
    private fun postProcess(words: List<String>): String {
        if (words.isEmpty()) return ""

        val result = words.toMutableList()

        // Capitalize first word
        result[0] = result[0].replaceFirstChar { ch ->
            if (ch.isLowerCase()) ch.titlecase() else ch.toString()
        }

        // Capitalize 'i' when standalone
        for (i in result.indices) {
            if (result[i] == "i" || result[i] == "i'm" || result[i] == "i'll" || result[i] == "i've" || result[i] == "i'd") {
                result[i] = result[i].replaceFirstChar { it.titlecase() }
            }
        }

        // Capitalize after sentence-ending punctuation
        for (i in 1 until result.size) {
            val prev = result[i - 1]
            if (prev.endsWith('.') || prev.endsWith('!') || prev.endsWith('?')) {
                result[i] = result[i].replaceFirstChar { ch ->
                    if (ch.isLowerCase()) ch.titlecase() else ch.toString()
                }
            }
        }

        // Ensure ending punctuation
        val lastWord = result.last()
        if (!lastWord.endsWith('.') && !lastWord.endsWith('!') && !lastWord.endsWith('?')) {
            result[result.size - 1] = lastWord + "."
        }

        return result.joinToString(" ")
    }

    /**
     * Generate a novel response influenced by category and mood.
     *
     * @param category Optional question category to bias starter selection
     * @param maxWords Maximum number of words to generate (default 25)
     * @return A generated oracle-style response string
     */
    fun generate(
        category: QuestionCategory? = null,
        maxWords: Int = 25
    ): String {
        repeat(3) {
            val result = tryGenerate(category, maxWords)
            if (result != null) return result
        }
        // Fallback to a random training sentence
        return fallbackResponses[random.nextInt(fallbackResponses.size)]
    }

    private fun tryGenerate(category: QuestionCategory?, maxWords: Int): String? {
        val starter = pickStarter(category)
        val words = mutableListOf(starter.first, starter.second)
        var current = starter

        for (step in 0 until maxWords - 2) {
            val next = sampleNext(current) ?: break
            words.add(next)

            // Stop at sentence-ending punctuation if we have enough words
            if (words.size >= 8 && next.matches(Regex(".*[.!?]$"))) {
                break
            }

            current = Pair(current.second, next)
        }

        // Quality checks
        if (words.size < 5) return null
        if (!containsVerb(words)) return null

        return postProcess(words)
    }
}
