package com.brewtech.decidr.intelligence

/**
 * Lightweight AFINN-inspired sentiment analyzer.
 * Pure Kotlin, no external dependencies, <1ms execution.
 * Scores text from -1.0 (very negative) to +1.0 (very positive).
 */
object SentimentAnalyzer {

    /**
     * Analyze text and return a sentiment score from -1.0 to +1.0.
     */
    fun analyze(text: String): Float {
        if (text.isBlank()) return 0.0f

        val normalized = text.lowercase().trim()
        val tokens = tokenize(normalized)
        if (tokens.isEmpty()) return 0.0f

        var totalScore = 0.0f
        var scoredTokens = 0
        var i = 0

        while (i < tokens.size) {
            val token = tokens[i]

            // Check for two-word phrases first
            if (i + 1 < tokens.size) {
                val bigram = "$token ${tokens[i + 1]}"
                val phraseScore = PHRASES[bigram]
                if (phraseScore != null) {
                    totalScore += phraseScore
                    scoredTokens++
                    i += 2
                    continue
                }
            }

            val baseScore = LEXICON[token]
            if (baseScore != null) {
                var wordScore = baseScore.toFloat()

                // Check for preceding negator
                if (i > 0 && tokens[i - 1] in NEGATORS) {
                    wordScore = -wordScore * 0.75f
                }

                // Check for preceding intensifier
                if (i > 0 && tokens[i - 1] in INTENSIFIERS) {
                    wordScore *= 1.5f
                }

                // Check for preceding diminisher
                if (i > 0 && tokens[i - 1] in DIMINISHERS) {
                    wordScore *= 0.5f
                }

                totalScore += wordScore
                scoredTokens++
            }

            i++
        }

        if (scoredTokens == 0) return 0.0f

        // Weighted average, clamped to [-1, 1]
        val raw = totalScore / scoredTokens.toFloat()
        return raw.coerceIn(-1.0f, 1.0f)
    }

    /**
     * Classify the overall mood of the text.
     */
    fun getMood(text: String): QuestionMood {
        if (text.isBlank()) return QuestionMood.NEUTRAL

        // Check urgency signals first (punctuation, caps)
        if (isUrgent(text)) return QuestionMood.URGENT

        // Check anxiety phrases
        if (isAnxious(text)) return QuestionMood.ANXIOUS

        val score = analyze(text)
        return when {
            score > 0.15f -> QuestionMood.POSITIVE
            score < -0.15f -> QuestionMood.NEGATIVE
            else -> QuestionMood.NEUTRAL
        }
    }

    // -- Internal helpers --

    private fun tokenize(text: String): List<String> {
        return text
            .replace(Regex("[^a-z'\\s]"), " ")
            .split(Regex("\\s+"))
            .filter { it.isNotBlank() && it.length > 1 }
            .map { it.trimEnd('\'').trimStart('\'') }
    }

    private fun isUrgent(text: String): Boolean {
        // Multiple exclamation marks
        if (text.contains("!!!") || text.contains("??")) return true
        // Significant portion in ALL CAPS (at least 2 words)
        val words = text.split(Regex("\\s+"))
        val capsWords = words.count { it.length > 2 && it == it.uppercase() && it.any { c -> c.isLetter() } }
        if (capsWords >= 2 && capsWords.toFloat() / words.size > 0.3f) return true
        // Urgency keywords
        val lower = text.lowercase()
        val urgencyPhrases = listOf("right now", "immediately", "asap", "hurry", "urgent", "emergency", "help me now", "seriously")
        return urgencyPhrases.any { lower.contains(it) }
    }

    private fun isAnxious(text: String): Boolean {
        val lower = text.lowercase()
        val anxietyPhrases = listOf(
            "what if", "i'm scared", "im scared", "i am scared",
            "worried about", "i'm worried", "im worried", "i am worried",
            "afraid of", "i'm afraid", "im afraid", "i am afraid",
            "nervous about", "i'm nervous", "im nervous",
            "anxious about", "i'm anxious", "im anxious",
            "what happens if", "should i be worried",
            "is it bad", "am i going to", "will i ever",
            "i can't stop thinking", "i cant stop thinking",
            "freaking out", "panicking", "panic",
            "scared to", "afraid to", "terrified",
            "i don't know what to do", "i dont know what to do",
            "help me", "what do i do", "what should i do"
        )
        return anxietyPhrases.any { lower.contains(it) }
    }

    // -- Word lists --

    private val NEGATORS: Set<String> = setOf(
        "not", "no", "never", "don't", "dont", "doesn't", "doesnt",
        "didn't", "didnt", "won't", "wont", "can't", "cant",
        "shouldn't", "shouldnt", "wouldn't", "wouldnt", "couldn't", "couldnt",
        "hardly", "barely", "neither", "nor", "isn't", "isnt",
        "aren't", "arent", "wasn't", "wasnt", "weren't", "werent",
        "hasn't", "hasnt", "haven't", "havent", "hadn't", "hadnt",
        "nothing", "nobody", "nowhere", "none"
    )

    private val INTENSIFIERS: Set<String> = setOf(
        "very", "really", "extremely", "incredibly", "absolutely",
        "totally", "completely", "utterly", "highly", "deeply",
        "truly", "remarkably", "enormously", "immensely", "intensely",
        "exceptionally", "extraordinarily", "tremendously", "severely",
        "awfully", "terribly", "seriously", "super", "so", "quite",
        "especially", "particularly", "most", "fucking", "freaking"
    )

    private val DIMINISHERS: Set<String> = setOf(
        "slightly", "somewhat", "barely", "hardly", "marginally",
        "a little", "kind of", "sort of", "mildly", "partially",
        "fairly", "rather", "moderately", "almost", "nearly",
        "just", "only", "merely", "faintly", "vaguely"
    )

    private val PHRASES: Map<String, Float> = mapOf(
        "fed up" to -3.0f,
        "broken up" to -3.0f,
        "break up" to -3.0f,
        "let down" to -3.0f,
        "given up" to -2.0f,
        "give up" to -2.0f,
        "ripped off" to -3.0f,
        "pissed off" to -4.0f,
        "worn out" to -2.0f,
        "burned out" to -3.0f,
        "stressed out" to -3.0f,
        "freaked out" to -3.0f,
        "messed up" to -3.0f,
        "screwed up" to -3.0f,
        "shut down" to -2.0f,
        "kicked out" to -3.0f,
        "turned down" to -2.0f,
        "passed away" to -4.0f,
        "sick of" to -3.0f,
        "tired of" to -2.0f,
        "end up" to -1.0f,
        "look forward" to 3.0f,
        "looking forward" to 3.0f,
        "cheer up" to 2.0f,
        "work out" to 2.0f,
        "figure out" to 1.0f,
        "make up" to 1.0f,
        "stand up" to 1.0f,
        "come together" to 2.0f,
        "well done" to 3.0f,
        "good job" to 3.0f,
        "great job" to 4.0f,
        "no good" to -3.0f,
        "no way" to -2.0f,
        "not fair" to -3.0f,
        "on top" to 2.0f,
        "at peace" to 3.0f,
        "in love" to 4.0f
    )

    /**
     * AFINN-inspired lexicon: 500+ words scored from -5 to +5.
     */
    private val LEXICON: Map<String, Int> = mapOf(
        // ===== POSITIVE EMOTIONS =====
        "happy" to 3,
        "happiness" to 3,
        "happily" to 3,
        "joy" to 3,
        "joyful" to 3,
        "joyous" to 3,
        "love" to 3,
        "loved" to 3,
        "loving" to 3,
        "lovely" to 3,
        "like" to 1,
        "liked" to 1,
        "great" to 3,
        "wonderful" to 4,
        "amazing" to 4,
        "awesome" to 4,
        "fantastic" to 4,
        "fabulous" to 4,
        "excellent" to 4,
        "outstanding" to 5,
        "incredible" to 4,
        "magnificent" to 4,
        "marvelous" to 4,
        "superb" to 4,
        "brilliant" to 4,
        "splendid" to 3,
        "glorious" to 3,
        "beautiful" to 3,
        "beauty" to 3,
        "gorgeous" to 3,
        "pretty" to 2,
        "elegant" to 2,
        "perfect" to 3,
        "perfectly" to 3,
        "paradise" to 3,
        "excited" to 3,
        "exciting" to 3,
        "excitement" to 3,
        "thrilled" to 4,
        "thrilling" to 4,
        "ecstatic" to 4,
        "elated" to 4,
        "euphoric" to 4,
        "overjoyed" to 4,
        "delighted" to 4,
        "delightful" to 3,
        "pleased" to 2,
        "pleasant" to 2,
        "glad" to 2,
        "cheerful" to 2,
        "cheery" to 2,
        "merry" to 2,
        "blissful" to 3,
        "bliss" to 3,
        "content" to 2,
        "contented" to 2,
        "satisfied" to 2,
        "satisfying" to 2,
        "fulfilling" to 3,
        "fulfilled" to 3,
        "grateful" to 3,
        "gratitude" to 3,
        "thankful" to 2,
        "blessed" to 3,
        "blessing" to 3,
        "hope" to 2,
        "hopeful" to 2,
        "hoping" to 1,
        "optimistic" to 2,
        "optimism" to 2,
        "positive" to 2,
        "confident" to 2,
        "confidence" to 2,
        "proud" to 2,
        "pride" to 2,
        "inspired" to 3,
        "inspiring" to 3,
        "inspiration" to 3,
        "motivated" to 2,
        "motivation" to 2,
        "encouraged" to 2,
        "encouraging" to 2,
        "enthusiastic" to 3,
        "enthusiasm" to 3,
        "passionate" to 3,
        "passion" to 2,
        "caring" to 2,
        "kind" to 2,
        "kindness" to 2,
        "generous" to 2,
        "generosity" to 2,
        "compassion" to 2,
        "compassionate" to 2,
        "empathy" to 2,
        "gentle" to 2,
        "warm" to 2,
        "warmth" to 2,
        "sweet" to 2,
        "tender" to 2,
        "affection" to 3,
        "affectionate" to 3,
        "adore" to 3,
        "adored" to 3,
        "cherish" to 3,
        "cherished" to 3,
        "treasure" to 2,
        "valued" to 2,
        "valuable" to 2,
        "worthy" to 2,
        "wonderful" to 4,
        "peaceful" to 2,
        "peace" to 2,
        "calm" to 1,
        "serene" to 2,
        "tranquil" to 2,
        "relaxed" to 2,
        "relaxing" to 2,
        "comfortable" to 2,
        "cozy" to 2,
        "safe" to 1,
        "secure" to 1,
        "stable" to 1,
        "free" to 1,
        "freedom" to 2,
        "liberated" to 2,
        "relief" to 2,
        "relieved" to 2,
        "soothing" to 2,
        "healed" to 2,
        "healing" to 2,
        "restored" to 2,
        "refreshed" to 2,
        "rejuvenated" to 2,
        "revitalized" to 2,
        "energized" to 2,
        "vibrant" to 2,
        "alive" to 1,
        "lively" to 2,

        // ===== POSITIVE ACTIONS / OUTCOMES =====
        "win" to 3,
        "won" to 3,
        "winning" to 3,
        "winner" to 3,
        "succeed" to 3,
        "success" to 4,
        "successful" to 4,
        "achieve" to 3,
        "achieved" to 3,
        "achievement" to 3,
        "accomplish" to 3,
        "accomplished" to 3,
        "accomplishment" to 3,
        "triumph" to 4,
        "victory" to 4,
        "progress" to 2,
        "improve" to 2,
        "improved" to 2,
        "improvement" to 2,
        "grow" to 1,
        "growth" to 2,
        "thrive" to 3,
        "thriving" to 3,
        "flourish" to 3,
        "prosper" to 3,
        "prosperity" to 3,
        "reward" to 2,
        "rewarding" to 2,
        "benefit" to 2,
        "beneficial" to 2,
        "advantage" to 2,
        "opportunity" to 2,
        "breakthrough" to 3,
        "miracle" to 4,
        "solution" to 1,
        "solved" to 2,
        "resolve" to 1,
        "resolved" to 2,
        "overcome" to 2,
        "conquered" to 2,

        // ===== SOCIAL POSITIVE =====
        "friend" to 2,
        "friends" to 2,
        "friendship" to 2,
        "together" to 2,
        "community" to 1,
        "belong" to 1,
        "belonging" to 2,
        "connected" to 2,
        "connection" to 2,
        "support" to 2,
        "supported" to 2,
        "supportive" to 2,
        "trust" to 2,
        "trusted" to 2,
        "trustworthy" to 2,
        "loyal" to 2,
        "loyalty" to 2,
        "faithful" to 2,
        "devoted" to 2,
        "respect" to 2,
        "respected" to 2,
        "admire" to 3,
        "admired" to 3,
        "welcome" to 2,
        "welcomed" to 2,
        "accepted" to 2,
        "included" to 1,
        "embraced" to 2,
        "forgive" to 2,
        "forgiven" to 2,
        "forgiveness" to 2,
        "reconcile" to 2,
        "harmony" to 2,
        "united" to 2,
        "bond" to 2,
        "bonded" to 2,
        "romance" to 2,
        "romantic" to 2,
        "engaged" to 2,
        "married" to 2,
        "wedding" to 3,
        "honeymoon" to 3,
        "anniversary" to 2,
        "soulmate" to 3,
        "partner" to 1,
        "family" to 1,

        // ===== CAREER POSITIVE =====
        "promotion" to 3,
        "promoted" to 3,
        "raise" to 3,
        "hired" to 2,
        "hire" to 1,
        "career" to 1,
        "opportunity" to 2,
        "bonus" to 3,
        "award" to 3,
        "awarded" to 3,
        "recognition" to 2,
        "recognized" to 2,
        "talent" to 2,
        "talented" to 2,
        "skilled" to 2,
        "expert" to 2,
        "mastery" to 3,
        "leader" to 2,
        "leadership" to 2,
        "mentor" to 2,
        "graduate" to 2,
        "graduated" to 2,
        "degree" to 1,
        "scholarship" to 3,
        "dream" to 2,
        "ambition" to 2,
        "ambitious" to 2,

        // ===== HEALTH POSITIVE =====
        "healthy" to 3,
        "health" to 1,
        "strong" to 2,
        "strength" to 2,
        "energy" to 2,
        "energetic" to 2,
        "fit" to 2,
        "fitness" to 2,
        "recovery" to 2,
        "recovered" to 3,
        "cured" to 3,
        "wellness" to 2,
        "vitality" to 2,
        "vigorous" to 2,
        "resilient" to 2,
        "resilience" to 2,

        // ===== FUN / ENTERTAINMENT =====
        "fun" to 3,
        "funny" to 2,
        "laugh" to 2,
        "laughing" to 2,
        "laughter" to 2,
        "humor" to 2,
        "hilarious" to 3,
        "enjoy" to 2,
        "enjoyed" to 2,
        "enjoyable" to 2,
        "entertaining" to 2,
        "entertainment" to 1,
        "celebrate" to 3,
        "celebration" to 3,
        "party" to 2,
        "festival" to 2,
        "vacation" to 2,
        "holiday" to 2,
        "adventure" to 2,
        "adventurous" to 2,
        "explore" to 1,
        "discovery" to 2,
        "surprise" to 1,
        "gift" to 2,
        "treat" to 2,
        "play" to 1,
        "playful" to 2,

        // ===== AGREEMENT / AFFIRMATION =====
        "yes" to 1,
        "sure" to 1,
        "agree" to 1,
        "agreed" to 1,
        "correct" to 1,
        "right" to 1,
        "true" to 1,
        "fair" to 1,
        "okay" to 1,
        "good" to 2,
        "fine" to 0,
        "nice" to 2,
        "best" to 3,
        "better" to 2,
        "thanks" to 2,
        "thank" to 2,
        "please" to 1,
        "appreciate" to 2,
        "appreciated" to 2,

        // ===== NEGATIVE EMOTIONS =====
        "sad" to -2,
        "sadness" to -2,
        "sadly" to -2,
        "unhappy" to -2,
        "miserable" to -4,
        "misery" to -4,
        "depressed" to -4,
        "depressing" to -3,
        "depression" to -4,
        "gloomy" to -2,
        "gloom" to -2,
        "melancholy" to -2,
        "sorrow" to -3,
        "sorrowful" to -3,
        "grief" to -4,
        "grieving" to -3,
        "mourning" to -3,
        "heartbreak" to -4,
        "heartbroken" to -4,
        "devastated" to -4,
        "devastation" to -4,
        "crushing" to -3,
        "crushed" to -3,
        "shattered" to -3,
        "broken" to -2,
        "defeated" to -3,
        "hopeless" to -4,
        "helpless" to -3,
        "powerless" to -3,
        "worthless" to -4,
        "useless" to -3,
        "pointless" to -3,
        "meaningless" to -3,
        "empty" to -2,
        "lonely" to -3,
        "loneliness" to -3,
        "alone" to -2,
        "isolated" to -3,
        "abandoned" to -3,
        "neglected" to -3,
        "rejected" to -3,
        "rejection" to -3,
        "unwanted" to -3,
        "unloved" to -3,
        "ignored" to -2,
        "invisible" to -2,
        "forgotten" to -2,
        "lost" to -2,
        "confused" to -2,
        "confusion" to -2,
        "uncertain" to -1,
        "doubt" to -1,
        "doubtful" to -2,
        "insecure" to -2,
        "insecurity" to -2,
        "vulnerable" to -2,
        "weak" to -2,
        "weakness" to -2,
        "fragile" to -2,
        "cry" to -2,
        "crying" to -3,
        "cried" to -2,
        "tears" to -2,
        "weep" to -3,
        "weeping" to -3,
        "sob" to -3,
        "sobbing" to -3,
        "suffer" to -3,
        "suffering" to -3,
        "pain" to -3,
        "painful" to -3,
        "agony" to -4,
        "agonizing" to -4,
        "torment" to -4,
        "torture" to -4,
        "anguish" to -4,
        "distress" to -3,
        "distressed" to -3,
        "troubled" to -2,
        "trouble" to -2,
        "struggling" to -2,
        "struggle" to -2,
        "hardship" to -3,
        "burden" to -2,
        "burdened" to -2,
        "overwhelmed" to -3,
        "overwhelming" to -2,
        "exhausted" to -2,
        "exhausting" to -2,
        "drained" to -2,
        "tired" to -2,
        "fatigue" to -2,
        "burnt" to -2,
        "burnout" to -3,
        "numb" to -2,
        "trapped" to -3,
        "stuck" to -2,
        "suffocating" to -3,
        "drowning" to -3,
        "sinking" to -2,
        "falling" to -1,

        // ===== ANGER =====
        "angry" to -3,
        "anger" to -3,
        "hate" to -4,
        "hated" to -4,
        "hatred" to -4,
        "hating" to -4,
        "loathe" to -4,
        "despise" to -4,
        "detest" to -4,
        "furious" to -4,
        "fury" to -4,
        "rage" to -4,
        "raging" to -4,
        "enraged" to -4,
        "outraged" to -4,
        "outrage" to -4,
        "livid" to -4,
        "mad" to -3,
        "irritated" to -2,
        "irritating" to -3,
        "annoyed" to -2,
        "annoying" to -3,
        "frustrated" to -2,
        "frustrating" to -3,
        "frustration" to -3,
        "agitated" to -2,
        "hostile" to -3,
        "hostility" to -3,
        "aggressive" to -2,
        "aggression" to -3,
        "violent" to -4,
        "violence" to -4,
        "bitter" to -3,
        "bitterness" to -3,
        "resentful" to -3,
        "resentment" to -3,
        "vengeful" to -3,
        "revenge" to -3,
        "spite" to -3,
        "spiteful" to -3,
        "jealous" to -2,
        "jealousy" to -2,
        "envious" to -2,
        "envy" to -2,

        // ===== FEAR / ANXIETY =====
        "afraid" to -3,
        "scared" to -3,
        "scary" to -2,
        "fear" to -3,
        "fearful" to -3,
        "frightened" to -3,
        "terrified" to -4,
        "terrifying" to -4,
        "horror" to -4,
        "horrible" to -4,
        "horrified" to -4,
        "horrifying" to -4,
        "dread" to -3,
        "dreading" to -3,
        "panic" to -4,
        "panicking" to -4,
        "panicked" to -4,
        "anxious" to -2,
        "anxiety" to -3,
        "nervous" to -2,
        "nervousness" to -2,
        "worried" to -2,
        "worry" to -2,
        "worrying" to -2,
        "concern" to -1,
        "concerned" to -1,
        "uneasy" to -2,
        "tense" to -2,
        "tension" to -2,
        "stressed" to -2,
        "stress" to -2,
        "stressful" to -3,
        "paranoid" to -3,
        "paranoia" to -3,
        "suspicious" to -2,
        "threatened" to -3,
        "threatening" to -3,
        "danger" to -3,
        "dangerous" to -3,
        "risk" to -1,
        "risky" to -2,
        "unsafe" to -3,

        // ===== DISGUST =====
        "disgusting" to -4,
        "disgusted" to -3,
        "disgust" to -3,
        "revolting" to -4,
        "repulsive" to -4,
        "gross" to -3,
        "nasty" to -3,
        "vile" to -4,
        "foul" to -3,
        "sickening" to -3,
        "repugnant" to -4,
        "abhorrent" to -4,
        "appalling" to -4,
        "atrocious" to -4,
        "hideous" to -3,
        "ugly" to -2,
        "filthy" to -3,
        "dirty" to -2,
        "corrupt" to -3,
        "corruption" to -3,
        "rotten" to -3,
        "putrid" to -4,
        "toxic" to -3,
        "poison" to -3,
        "poisonous" to -3,

        // ===== RELATIONSHIP NEGATIVE =====
        "breakup" to -3,
        "divorce" to -3,
        "divorced" to -3,
        "separated" to -2,
        "separation" to -2,
        "cheat" to -4,
        "cheated" to -4,
        "cheating" to -4,
        "cheater" to -4,
        "unfaithful" to -4,
        "affair" to -3,
        "betray" to -4,
        "betrayed" to -4,
        "betrayal" to -4,
        "liar" to -3,
        "lie" to -2,
        "lying" to -3,
        "lies" to -3,
        "dishonest" to -3,
        "manipulate" to -3,
        "manipulated" to -3,
        "manipulation" to -3,
        "manipulative" to -3,
        "controlling" to -3,
        "abusive" to -4,
        "abuse" to -4,
        "abused" to -4,
        "toxic" to -3,
        "gaslighting" to -4,
        "ghosted" to -3,
        "ghosting" to -3,
        "heartless" to -3,
        "cruel" to -4,
        "cruelty" to -4,
        "mean" to -2,
        "bully" to -3,
        "bullied" to -3,
        "bullying" to -3,
        "harass" to -4,
        "harassed" to -4,
        "harassment" to -4,
        "stalk" to -4,
        "stalking" to -4,

        // ===== CAREER NEGATIVE =====
        "fired" to -4,
        "laid" to -1,
        "layoff" to -3,
        "layoffs" to -3,
        "unemployed" to -3,
        "unemployment" to -3,
        "jobless" to -3,
        "quit" to -2,
        "quitting" to -2,
        "demoted" to -3,
        "demotion" to -3,
        "rejected" to -3,
        "underpaid" to -2,
        "overworked" to -3,
        "exploited" to -3,
        "exploitation" to -3,
        "bankrupt" to -4,
        "bankruptcy" to -4,
        "debt" to -2,
        "broke" to -2,
        "poor" to -2,
        "poverty" to -3,
        "homeless" to -3,
        "evicted" to -3,
        "foreclosure" to -3,

        // ===== HEALTH NEGATIVE =====
        "sick" to -3,
        "sickness" to -3,
        "ill" to -2,
        "illness" to -3,
        "disease" to -3,
        "infected" to -3,
        "infection" to -3,
        "cancer" to -4,
        "tumor" to -4,
        "dying" to -4,
        "death" to -4,
        "dead" to -4,
        "die" to -4,
        "died" to -4,
        "killed" to -4,
        "kill" to -4,
        "fatal" to -4,
        "terminal" to -4,
        "chronic" to -2,
        "disabled" to -2,
        "disability" to -2,
        "injured" to -3,
        "injury" to -3,
        "wound" to -3,
        "wounded" to -3,
        "bleeding" to -2,
        "hospital" to -2,
        "surgery" to -2,
        "overdose" to -4,
        "addiction" to -3,
        "addicted" to -3,
        "withdrawal" to -2,
        "relapse" to -3,
        "suicidal" to -5,
        "suicide" to -5,
        "selfharm" to -5,

        // ===== GENERAL NEGATIVE =====
        "bad" to -2,
        "worse" to -3,
        "worst" to -4,
        "terrible" to -4,
        "awful" to -4,
        "dreadful" to -4,
        "horrible" to -4,
        "horrendous" to -4,
        "pathetic" to -3,
        "lousy" to -2,
        "mediocre" to -1,
        "inferior" to -2,
        "wrong" to -2,
        "mistake" to -2,
        "mistakes" to -2,
        "fail" to -3,
        "failed" to -3,
        "failure" to -3,
        "disaster" to -4,
        "catastrophe" to -4,
        "catastrophic" to -4,
        "crisis" to -3,
        "problem" to -2,
        "problems" to -2,
        "issue" to -1,
        "issues" to -1,
        "difficult" to -1,
        "difficulty" to -2,
        "hard" to -1,
        "impossible" to -3,
        "complicated" to -1,
        "complex" to -1,
        "mess" to -2,
        "messy" to -2,
        "chaos" to -3,
        "chaotic" to -3,
        "ruined" to -3,
        "ruin" to -3,
        "destroyed" to -4,
        "destroy" to -4,
        "destruction" to -4,
        "damage" to -3,
        "damaged" to -3,
        "harm" to -3,
        "harmed" to -3,
        "harmful" to -3,
        "hurt" to -3,
        "hurting" to -3,
        "loss" to -3,
        "lose" to -3,
        "losing" to -3,
        "loser" to -3,
        "waste" to -2,
        "wasted" to -2,
        "regret" to -3,
        "regretful" to -3,
        "remorse" to -2,
        "guilt" to -3,
        "guilty" to -3,
        "shame" to -3,
        "ashamed" to -3,
        "embarrassed" to -2,
        "embarrassing" to -2,
        "embarrassment" to -2,
        "humiliated" to -4,
        "humiliation" to -4,

        // ===== PROFANITY / STRONG NEGATIVE =====
        "damn" to -2,
        "shit" to -3,
        "crap" to -2,
        "hell" to -2,
        "ass" to -2,
        "suck" to -2,
        "sucks" to -3,
        "sucked" to -3,
        "stupid" to -3,
        "idiot" to -3,
        "dumb" to -3,
        "moron" to -3,
        "fool" to -2,
        "foolish" to -2,
        "ridiculous" to -2,
        "absurd" to -2,
        "nonsense" to -2,
        "bullshit" to -4,
        "scam" to -3,
        "fraud" to -4,
        "fake" to -3,
        "phony" to -3,
        "trash" to -3,
        "garbage" to -3,
        "junk" to -2,
        "worthless" to -4,
        "pathetic" to -3,
        "lame" to -2,

        "whatever" to -1,
        "help" to -2,
        "honestly" to 0,

        // ===== UNCERTAINTY / DOUBT =====
        "maybe" to 0,
        "perhaps" to 0,
        "possibly" to 0,
        "unsure" to -1,
        "unclear" to -1,
        "unknown" to -1,
        "wondering" to 0,
        "wonder" to 0,
        "question" to 0,
        "curious" to 1,
        "curiosity" to 1,

        // ===== MIXED / CONTEXT-DEPENDENT =====
        "change" to 0,
        "different" to 0,
        "new" to 1,
        "old" to 0,
        "start" to 1,
        "end" to -1,
        "stop" to -1,
        "wait" to -1,
        "need" to -1,
        "want" to 0,
        "wish" to 0,
        "miss" to -2,
        "missing" to -2,
        "remember" to 0,
        "forget" to -1,
        "sorry" to -1,
        "apologize" to -1,
        "apology" to -1
    )
}

/**
 * Mood classification for analyzed text.
 */
enum class QuestionMood {
    /** Hopeful, excited, optimistic tone */
    POSITIVE,
    /** Worried, sad, angry tone */
    NEGATIVE,
    /** Factual, calm tone */
    NEUTRAL,
    /** Scared, nervous, uncertain tone */
    ANXIOUS,
    /** Demanding, impatient tone */
    URGENT
}
